import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class FontService {

  constructor() {}

  private readonly FONTS = [
    "Abel",
    "Agency FB",
    "Alegreya",
    "Andale Mono",
    "Anton",
    "Archivo",
    "Arial",
    "Arial Black",
    "Arial Narrow",
    "Asap",
    "Baskerville Old Face",
    "Bebas Neue",
    "Berlin Sans FB",
    "Bitter",
    "Book Antiqua",
    "Bookman Old Style",
    "Bradley Hand ITC",
    "Brush Script MT",
    "Cabin",
    "Cairo",
    "Calisto MT",
    "Cambria",
    "Candara",
    "Caveat",
    "Century Gothic",
    "Century Schoolbook",
    "Chivo",
    "Cinzel",
    "Coda",
    "Colonna MT",
    "Comfortaa",
    "Comic Sans MS",
    "Consolas",
    "Copperplate Gothic Bold",
    "Courier New",
    "Crimson Text",
    "Cuprum",
    "Dosis",
    "Edwardian Script ITC",
    "Exo",
    "Felix Titling",
    "Fira Sans",
    "Fjalla One",
    "Footlight MT Light",
    "Franklin Gothic Medium",
    "Freestyle Script",
    "French Script MT",
    "Garamond",
    "Geneva",
    "Georgia",
    "Gigi",
    "Harlow Solid Italic",
    "Harrington",
    "Helvetica",
    "High Tower Text",
    "Hind",
    "Impact",
    "Inconsolata",
    "Jokerman",
    "Josefin Sans",
    "Juice ITC",
    "Karla",
    "Kristen ITC",
    "Lato",
    "Libre Franklin",
    "Lobster",
    "Lobster Two",
    "Lora",
    "Lucida Bright",
    "Lucida Console",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "MS Gothic",
    "MS Mincho",
    "MS PGothic",
    "MS PMincho",
    "MS Reference Sans Serif",
    "MS Sans Serif",
    "MS Serif",
    "MS UI Gothic",
    "Matura MT Script Capitals",
    "Merriweather",
    "Mistral",
    "Modern No. 20",
    "Monotype Corsiva",
    "Montserrat",
    "Muli",
    "Niagara Engraved",
    "Noto Sans",
    "Nunito",
    "Old English Text MT",
    "Onyx",
    "Open Sans",
    "Optima",
    "Oswald",
    "PT Sans",
    "Pacifico",
    "Palatino Linotype",
    "Papyrus",
    "Parchment",
    "Perpetua",
    "Playbill",
    "Playfair Display",
    "Poppins",
    "Questrial",
    "Quicksand",
    "Raleway",
    "Ravie",
    "Roboto",
    "Rockwell",
    "Rockwell Extra Bold",
    "Rubik",
    "Script MT Bold",
    "Segoe UI",
    "Showcard Gothic",
    "Snap ITC",
    "Source Sans Pro",
    "Stencil",
    "Stencil Std",
    "Tahoma",
    "Times New Roman",
    "Titillium Web",
    "Trebuchet MS",
    "Tw Cen MT",
    "Ubuntu",
    "Varela Round",
    "Verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Webdings",
    "Wide Latin",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3",
    "Work Sans",
    "Zapf Chancery",
    "Zapf Dingbats"
  ];

  /**
   * Retourne une liste de polices triées par ordre alphabétique
   */
  public getFonts(): string[] {
    return this.FONTS.sort();
  }
}
